FullAdder_4bit: FullAdder.v FullAdder_4bit.v FullAdder_tb.v
	iverilog -o FullAdder_4bit FullAdder.v FullAdder_4bit.v FullAdder_tb.v
	./FullAdder_4bit

clean: 
	rm -f FullAdder_4bit *~ *.vcd

.PHONY: clean all
